General:
    comment: N0 vs N+
    seed: 2021
    fp16: False
    amp_level: O2
    precision: 32
    multi_gpu_mode: dp
    gpus: [0]
    epochs: &epoch 200
    grad_acc: 20
    frozen_bn: False
    patience: 20
    server: train #train #test
    log_path: logs/

Data:
    dataset_name: camel_data
    data_shuffle: True
    data_dir: clam_patches/pt_files_512/
    label_dir: dataset_csv/bcnb/
    # fold 0: normal ER, fold 1: N0 vs N+, fold 2: normal ER, fold 3: real ER
    fold: 1
    nfold: 4

    train_dataloader:
        batch_size: 1
        num_workers: 8

    test_dataloader:
        batch_size: 1
        num_workers: 8

Model:
    name: TransMIL
    n_classes: 2


Optimizer:
    opt: lookahead_radam
    lr: 0.002
    opt_eps: null
    opt_betas: null
    momentum: null 
    weight_decay: 0.00001

Loss:
    base_loss: CrossEntropyLoss

